### ISSUE TITLE
catkin_make

### ISSUE THREAD

**Issue by ZhangJunfeng199** [YikangZhang1641/HybridAStarSearch#1]
use catkin_make show can't find "costmap_converter/ObstacleArrayMsg.h",

**Comment by A-luckyGaY** [comment]
me too

**Comment by YikangZhang1641** [comment]
sudo apt install ros-(yourversion)-costmap-converter

**Comment by YikangZhang1641** [comment]
sudo apt install ros-(yourversion)-costmap-converter
